hydra:  
  output_subdir: null  
  run:  
    dir: .

raw: 
  path: data/raw/dataset.csv

processed:
  dir: data/processed
  name: processed.csv
  path: ${processed.dir}/${processed.name}

final:
  dir: data/final
  name: final.csv
  path: ${final.dir}/${final.name}