hydra:  
  output_subdir: null  
  run:  
    dir: .

raw: 
  path: data/raw/dataset.csv

processed:
  dir: data/processed
  name: final_selection.csv
  path: ${processed.dir}/${processed.name}

model_input:
  dir: data/features_data
  name: model_input.csv
  path: ${model_input.dir}/${model_input.name}

parameters:
  var_thres: 0.005
