hydra:  
  output_subdir: null  
  run:  
    dir: .

defaults:
  - model: model
  - _self_

raw: 
  path: data/raw/dataset.csv

processed:
  dir: data/processed
  name: final_selection.csv
  path: ${processed.dir}/${processed.name}

model_input:
  dir: data/features_data
  name: model_input.csv
  path: ${model_input.dir}/${model_input.name}

parameters:
  var_thres: 0.0005

model:
  dir: models
  name: XGBoost
  path: ${model.dir}/${model.name}

pca:
  dir: models
  components: 8
  name: pca
  path: ${pca.dir}/${pca.name}

encoder:
  dir: models
  name: one_hot
  path: ${encoder.dir}/${encoder.name}

variance:
  dir: models
  name: vars
  path: ${variance.dir}/${variance.name}

feats:
  dir: models
  name: feat
  path: ${feats.dir}/${feats.name}

label_encoder:
  dir: models
  name: label_enc
  path: ${label_encoder.dir}/${label_encoder.name}




